### ISSUE TITLE
Snapshots with added proxy support

### ISSUE THREAD

**Issue by devanshdalal** [koldbyte/CodeBackup#2]
![app](https://cloud.githubusercontent.com/assets/5080310/12817606/dd7515bc-cb78-11e5-850c-036510ff5170.png)

**Comment by devanshdalal** [comment]
![img](https://cloud.githubusercontent.com/assets/5080310/12817628/f70b232c-cb78-11e5-927f-26a4b52449d0.png)

**Comment by koldbyte** [comment]
Nice.. you are the first contributor to my projects.

**Comment by devanshdalal** [comment]
thank you. You might want to merge my pull requests..?

**Comment by koldbyte** [comment]
Yes. I will merge it soon. Thanks for your contribution.

**Comment by koldbyte** [comment]
Just merged it. Can you check the proxy options? Try it for multiple runs with toggling proxy settings on and off every run.
Thanks.

**Comment by devanshdalal** [comment]
Yeah, I tried toggling and checked as you mentioned . It works. 

One possible issue can be if some download fails. It should move on to next problem instead of terminating. The entire process should not stop. I am not if this is already considered for all sites.

PS: I wanted to ask one more thing. Are you applying for GSOC this year?

**Comment by koldbyte** [comment]
Great. I hope you tried this after pulling my commits.
For the possible issue, Please try it through Fiddler Proxy. You will be able to cause deliberate failures and test.

Regarding the GSOC, no I won't be able to. Because I am no longer a student. I have a full time job now.
Do apply to GSOC if you can, its a great platform.
